language: node_js

node_js:
 - "stable"
 script:
  - npm test
  - npm run webpk

deploy:
 provider: s3
 access_key_id: $AWS_KEY
 secret_access_key: $AWS_SECRET
 bucket: "s3-fec-reviews"
 skip_cleanip: true
 acl: public_read
 local_dir: public
